import type { IconType } from 'react-icons'
import { FaHandshake, FaMapMarkerAlt, FaToilet, FaUsersSlash } from 'react-icons/fa'
import {
  GiAngelWings,
  GiBangingGavel,
  GiBarricade,
  GiBrokenShield,
  GiCage,
  GiCardRandom,
  GiChecklist,
  GiChurch,
  GiContract,
  GiDinosaurRex,
  GiDonkey,
  GiDragonSpiral,
  GiDrinking,
  GiElevator,
  GiFairyWings,
  GiFeather,
  GiFizzingFlask,
  GiGoblinHead,
  GiHandcuffs,
  GiHutsVillage,
  GiImpLaugh,
  GiLetterBomb,
  GiLifeBuoy,
  GiMineWagon,
  GiMonsterGrasp,
  GiMountaintop,
  GiNeedleDrill,
  GiNestBirds,
  GiPartyFlags,
  GiPassport,
  GiPathDistance,
  GiPlantsAndAnimals,
  GiPuzzle,
  GiRank2,
  GiRank3,
  GiRaven,
  GiSaberToothedCatHead,
  GiSailboat,
  GiScales,
  GiSecretBook,
  GiSecretDoor,
  GiShadowFollower,
  GiShadowGrasp,
  GiShamblingZombie,
  GiShatter,
  GiSheep,
  GiShipWheel,
  GiSpiderWeb,
  GiStable,
  GiSunrise,
  GiTavernSign,
  GiTeamUpgrade,
  GiTentaclesBarrier,
  GiTroll,
  GiVelociraptorTracks,
  GiWolfTrap,
  GiWoodAxe,
  GiWoodenSign,
} from 'react-icons/gi'

import { CUSTOM_ICONS } from '#/lib/custom-icons'

export const DAY_MARK_ICON = 'custom/LongRest'

/** Curated react-icons registry for timeline event marks. Keys use `set/IconName`. */
export const EVENT_ICONS: Record<string, IconType> = {
  'fa/FaHandshake': FaHandshake,
  'fa/FaMapMarkerAlt': FaMapMarkerAlt,
  'fa/FaToilet': FaToilet,
  'fa/FaUsersSlash': FaUsersSlash,
  'gi/GiAngelWings': GiAngelWings,
  'gi/GiBangingGavel': GiBangingGavel,
  'gi/GiBarricade': GiBarricade,
  'gi/GiBrokenShield': GiBrokenShield,
  'gi/GiCage': GiCage,
  'gi/GiCardRandom': GiCardRandom,
  'gi/GiChecklist': GiChecklist,
  'gi/GiChurch': GiChurch,
  'gi/GiContract': GiContract,
  'gi/GiDinosaurRex': GiDinosaurRex,
  'gi/GiDonkey': GiDonkey,
  'gi/GiDragonSpiral': GiDragonSpiral,
  'gi/GiDrinking': GiDrinking,
  'gi/GiElevator': GiElevator,
  'gi/GiFairyWings': GiFairyWings,
  'gi/GiFeather': GiFeather,
  'gi/GiFizzingFlask': GiFizzingFlask,
  'gi/GiGoblinHead': GiGoblinHead,
  'gi/GiHandcuffs': GiHandcuffs,
  'gi/GiHutsVillage': GiHutsVillage,
  'gi/GiImpLaugh': GiImpLaugh,
  'gi/GiLetterBomb': GiLetterBomb,
  'gi/GiLifeBuoy': GiLifeBuoy,
  'gi/GiMineWagon': GiMineWagon,
  'gi/GiMonsterGrasp': GiMonsterGrasp,
  'gi/GiMountaintop': GiMountaintop,
  'gi/GiNeedleDrill': GiNeedleDrill,
  'gi/GiNestBirds': GiNestBirds,
  'gi/GiPartyFlags': GiPartyFlags,
  'gi/GiPassport': GiPassport,
  'gi/GiPathDistance': GiPathDistance,
  'gi/GiPlantsAndAnimals': GiPlantsAndAnimals,
  'gi/GiPuzzle': GiPuzzle,
  'gi/GiRank2': GiRank2,
  'gi/GiRank3': GiRank3,
  'gi/GiRaven': GiRaven,
  'gi/GiSaberToothedCatHead': GiSaberToothedCatHead,
  'gi/GiSailboat': GiSailboat,
  'gi/GiScales': GiScales,
  'gi/GiSecretBook': GiSecretBook,
  'gi/GiSecretDoor': GiSecretDoor,
  'gi/GiShadowFollower': GiShadowFollower,
  'gi/GiShadowGrasp': GiShadowGrasp,
  'gi/GiShamblingZombie': GiShamblingZombie,
  'gi/GiShatter': GiShatter,
  'gi/GiSheep': GiSheep,
  'gi/GiShipWheel': GiShipWheel,
  'gi/GiSpiderWeb': GiSpiderWeb,
  'gi/GiStable': GiStable,
  'gi/GiSunrise': GiSunrise,
  'gi/GiTavernSign': GiTavernSign,
  'gi/GiTeamUpgrade': GiTeamUpgrade,
  'gi/GiTentaclesBarrier': GiTentaclesBarrier,
  'gi/GiTroll': GiTroll,
  'gi/GiVelociraptorTracks': GiVelociraptorTracks,
  'gi/GiWolfTrap': GiWolfTrap,
  'gi/GiWoodAxe': GiWoodAxe,
  'gi/GiWoodenSign': GiWoodenSign,
  [DAY_MARK_ICON]: CUSTOM_ICONS[DAY_MARK_ICON],
}

const DEFAULT_ICON = EVENT_ICONS['fa/FaMapMarkerAlt']

export function resolveEventIcon(name: string): IconType {
  return EVENT_ICONS[name] ?? DEFAULT_ICON
}

export function EventMarkIcon({ name, className }: { name: string; className?: string }) {
  const Icon = resolveEventIcon(name)
  return <Icon className={className} aria-hidden />
}
