import { MailWarning, Toilet } from 'lucide-react'
import type { ComponentType } from 'react'
import { FaHandshake, FaMapMarkerAlt, FaPrescriptionBottleAlt, FaUsersSlash } from 'react-icons/fa'
import {
  GiAngelWings,
  GiBarricade,
  GiBlast,
  GiBrokenShield,
  GiBridge,
  GiCage,
  GiCardRandom,
  GiCargoShip,
  GiChecklist,
  GiChurch,
  GiDaggers,
  GiDirewolf,
  GiDinosaurRex,
  GiDonkey,
  GiDoorway,
  GiDragonSpiral,
  GiDrinking,
  GiElevator,
  GiFairyWings,
  GiFeather,
  GiFizzingFlask,
  GiFloatingPlatforms,
  GiFloorHatch,
  GiGavel,
  GiGoblinHead,
  GiHutsVillage,
  GiImpLaugh,
  GiLifeBuoy,
  GiLightningStorm,
  GiLockpicks,
  GiMineWagon,
  GiMetalDisc,
  GiMonsterGrasp,
  GiMountaintop,
  GiNeedleDrill,
  GiNestBirds,
  GiPartyFlags,
  GiPassport,
  GiPathDistance,
  GiPlantsAndAnimals,
  GiPuzzle,
  GiPunch,
  GiPrisoner,
  GiProgression,
  GiRank2,
  GiRank3,
  GiRaven,
  GiSaberToothedCatHead,
  GiSailboat,
  GiScales,
  GiScrollQuill,
  GiSecretBook,
  GiShadowFollower,
  GiShadowGrasp,
  GiShamblingZombie,
  GiShatter,
  GiSheep,
  GiShipWheel,
  GiSpiderWeb,
  GiStable,
  GiSunrise,
  GiSuckeredTentacle,
  GiTavernSign,
  GiTeamUpgrade,
  GiTimeBomb,
  GiTrade,
  GiTroll,
  GiVelociraptorTracks,
  GiWoodAxe,
  GiWoodenSign,
} from 'react-icons/gi'

import { CUSTOM_ICONS } from '#/lib/custom-icons'

export const DAY_MARK_ICON = 'custom/LongRest'

type EventIcon = ComponentType<{ className?: string; 'aria-hidden'?: boolean }>

/** Curated icon-catalog registry for timeline event marks. */
export const EVENT_ICONS: Record<string, EventIcon> = {
  'fa/FaHandshake': FaHandshake,
  'fa/FaMapMarkerAlt': FaMapMarkerAlt,
  'fa/FaPrescriptionBottleAlt': FaPrescriptionBottleAlt,
  'fa/FaUsersSlash': FaUsersSlash,
  'lucide/MailWarning': MailWarning,
  'lucide/Toilet': Toilet,
  'gi/GiAngelWings': GiAngelWings,
  'gi/GiBarricade': GiBarricade,
  'gi/GiBlast': GiBlast,
  'gi/GiBrokenShield': GiBrokenShield,
  'gi/GiBridge': GiBridge,
  'gi/GiCage': GiCage,
  'gi/GiCardRandom': GiCardRandom,
  'gi/GiCargoShip': GiCargoShip,
  'gi/GiChecklist': GiChecklist,
  'gi/GiChurch': GiChurch,
  'gi/GiDaggers': GiDaggers,
  'gi/GiDirewolf': GiDirewolf,
  'gi/GiDinosaurRex': GiDinosaurRex,
  'gi/GiDonkey': GiDonkey,
  'gi/GiDoorway': GiDoorway,
  'gi/GiDragonSpiral': GiDragonSpiral,
  'gi/GiDrinking': GiDrinking,
  'gi/GiElevator': GiElevator,
  'gi/GiFairyWings': GiFairyWings,
  'gi/GiFeather': GiFeather,
  'gi/GiFizzingFlask': GiFizzingFlask,
  'gi/GiFloatingPlatforms': GiFloatingPlatforms,
  'gi/GiFloorHatch': GiFloorHatch,
  'gi/GiGavel': GiGavel,
  'gi/GiGoblinHead': GiGoblinHead,
  'gi/GiHutsVillage': GiHutsVillage,
  'gi/GiImpLaugh': GiImpLaugh,
  'gi/GiLifeBuoy': GiLifeBuoy,
  'gi/GiLightningStorm': GiLightningStorm,
  'gi/GiLockpicks': GiLockpicks,
  'gi/GiMineWagon': GiMineWagon,
  'gi/GiMetalDisc': GiMetalDisc,
  'gi/GiMonsterGrasp': GiMonsterGrasp,
  'gi/GiMountaintop': GiMountaintop,
  'gi/GiNeedleDrill': GiNeedleDrill,
  'gi/GiNestBirds': GiNestBirds,
  'gi/GiPartyFlags': GiPartyFlags,
  'gi/GiPassport': GiPassport,
  'gi/GiPathDistance': GiPathDistance,
  'gi/GiPlantsAndAnimals': GiPlantsAndAnimals,
  'gi/GiPuzzle': GiPuzzle,
  'gi/GiPunch': GiPunch,
  'gi/GiPrisoner': GiPrisoner,
  'gi/GiProgression': GiProgression,
  'gi/GiRank2': GiRank2,
  'gi/GiRank3': GiRank3,
  'gi/GiRaven': GiRaven,
  'gi/GiSaberToothedCatHead': GiSaberToothedCatHead,
  'gi/GiSailboat': GiSailboat,
  'gi/GiScales': GiScales,
  'gi/GiScrollQuill': GiScrollQuill,
  'gi/GiSecretBook': GiSecretBook,
  'gi/GiShadowFollower': GiShadowFollower,
  'gi/GiShadowGrasp': GiShadowGrasp,
  'gi/GiShamblingZombie': GiShamblingZombie,
  'gi/GiShatter': GiShatter,
  'gi/GiSheep': GiSheep,
  'gi/GiShipWheel': GiShipWheel,
  'gi/GiSpiderWeb': GiSpiderWeb,
  'gi/GiStable': GiStable,
  'gi/GiSunrise': GiSunrise,
  'gi/GiSuckeredTentacle': GiSuckeredTentacle,
  'gi/GiTavernSign': GiTavernSign,
  'gi/GiTeamUpgrade': GiTeamUpgrade,
  'gi/GiTimeBomb': GiTimeBomb,
  'gi/GiTrade': GiTrade,
  'gi/GiTroll': GiTroll,
  'gi/GiVelociraptorTracks': GiVelociraptorTracks,
  'gi/GiWoodAxe': GiWoodAxe,
  'gi/GiWoodenSign': GiWoodenSign,
  [DAY_MARK_ICON]: CUSTOM_ICONS[DAY_MARK_ICON],
}

const DEFAULT_ICON = EVENT_ICONS['fa/FaMapMarkerAlt']

export function resolveEventIcon(name: string): EventIcon {
  return EVENT_ICONS[name] ?? DEFAULT_ICON
}

export function EventMarkIcon({ name, className }: { name: string; className?: string }) {
  const Icon = resolveEventIcon(name)
  return <Icon className={className} aria-hidden />
}
