import {
  Building2,
  Castle,
  Cloud,
  BedSingle,
  Dock,
  FlaskConical,
  Gavel,
  House,
  Library,
  Map,
  MoonStar,
  Mountain,
  MountainSnow,
  Route,
  Ship,
  Sparkles,
  Trees,
  type LucideIcon,
} from 'lucide-react'
import type { ComponentType } from 'react'
import { FaDice, FaGlobe, FaHorse, FaMap, FaMapMarkerAlt, FaStoreAlt } from 'react-icons/fa'
import {
  GiAncientRuins,
  GiAlienEgg,
  GiAllSeeingEye,
  GiAnvilImpact,
  GiApothecary,
  GiBarn,
  GiBeerStein,
  GiBirdHouse,
  GiBridge,
  GiBunkBeds,
  GiBubblingFlask,
  GiByzantinTemple,
  GiCaravel,
  GiCastle,
  GiCaveEntrance,
  GiCauldron,
  GiChurch,
  GiCircleForest,
  GiCliffCrossing,
  GiCloudRing,
  GiCargoShip,
  GiCaptainHatProfile,
  GiDeathZone,
  GiDesk,
  GiDungeonGate,
  GiFamilyHouse,
  GiFairyWand,
  GiFloatingPlatforms,
  GiFloorHatch,
  GiGate,
  GiForest,
  GiGearHammer,
  GiGlowingArtifact,
  GiHarborDock,
  GiHidden,
  GiHutsVillage,
  GiIsland,
  GiKitchenKnives,
  GiMedievalBarracks,
  GiMedievalGate,
  GiMineWagon,
  GiMaze,
  GiFruitTree,
  GiDjedPillar,
  GiWaterfall,
  GiStonePath,
  GiCampfire,
  GiMountainCave,
  GiMountains,
  GiMountaintop,
  GiPuzzle,
  GiOpenGate,
  GiPokerHand,
  GiPrayer,
  GiSailboat,
  GiShadowGrasp,
  GiStoneTower,
  GiThroneKing,
  GiTripleGate,
  GiTwoShadows,
  GiSpectre,
  GiShop,
  GiShower,
  GiStable,
  GiStalactites,
  GiSwordsEmblem,
  GiTempleDoor,
  GiTempleGate,
  GiUndergroundCave,
  GiVillage,
  GiWaterFountain,
  GiWaves,
  GiWhirlwind,
  GiBlood,
} from 'react-icons/gi'

import { LOCATION_TYPE_LABELS, type LocationType } from '#/definitions/location.ts'
import { cn } from '#/lib/utils'

export const LOCATION_TYPE_ICONS: Record<LocationType, LucideIcon> = {
  settlement: Building2,
  region: Map,
  district: Building2,
  building: House,
  wilderness: Trees,
  dungeon: Castle,
  landmark: Mountain,
  realm: Sparkles,
  route: Route,
}

export function LocationTypeIcon({ type, className }: { type: LocationType; className?: string }) {
  const Icon = LOCATION_TYPE_ICONS[type]
  return <Icon className={cn('size-3.5 shrink-0', className)} aria-hidden />
}

export function locationTypeLabel(type: LocationType, plural = false): string {
  return plural ? LOCATION_TYPE_LABELS[type] : LOCATION_TYPE_LABELS[type].replace(/s$/, '')
}

/** Placeholder shown when a location has no `icon`. */
export const LOCATION_ICON_PLACEHOLDER = 'fa/FaMapMarkerAlt'

type LocationGlyph = ComponentType<{ className?: string; 'aria-hidden'?: boolean }>

/**
 * Curated react-icons registry for per-location avatars. Keys use `set/IconName`,
 * matching the event-icons convention. Each location picks a unique key via its
 * `icon` field; unknown/omitted keys fall back to the placeholder.
 */
export const LOCATION_ICONS: Record<string, LocationGlyph> = {
  'fa/FaDice': FaDice,
  'fa/FaGlobe': FaGlobe,
  'fa/FaHorse': FaHorse,
  'fa/FaMap': FaMap,
  'fa/FaStoreAlt': FaStoreAlt,
  'lucide/BedSingle': BedSingle,
  'lucide/Cloud': Cloud,
  'lucide/Dock': Dock,
  'lucide/FlaskConical': FlaskConical,
  'lucide/Gavel': Gavel,
  'lucide/Library': Library,
  'lucide/MountainSnow': MountainSnow,
  'lucide/MoonStar': MoonStar,
  'lucide/Ship': Ship,
  'gi/GiAlienEgg': GiAlienEgg,
  'gi/GiAllSeeingEye': GiAllSeeingEye,
  'gi/GiAncientRuins': GiAncientRuins,
  'gi/GiAnvilImpact': GiAnvilImpact,
  'gi/GiApothecary': GiApothecary,
  'gi/GiBarn': GiBarn,
  'gi/GiBeerStein': GiBeerStein,
  'gi/GiBirdHouse': GiBirdHouse,
  'gi/GiBridge': GiBridge,
  'gi/GiBunkBeds': GiBunkBeds,
  'gi/GiBubblingFlask': GiBubblingFlask,
  'gi/GiByzantinTemple': GiByzantinTemple,
  'gi/GiCaravel': GiCaravel,
  'gi/GiCastle': GiCastle,
  'gi/GiCaveEntrance': GiCaveEntrance,
  'gi/GiCauldron': GiCauldron,
  'gi/GiChurch': GiChurch,
  'gi/GiCircleForest': GiCircleForest,
  'gi/GiCliffCrossing': GiCliffCrossing,
  'gi/GiCloudRing': GiCloudRing,
  'gi/GiCargoShip': GiCargoShip,
  'gi/GiCaptainHatProfile': GiCaptainHatProfile,
  'gi/GiDeathZone': GiDeathZone,
  'gi/GiDesk': GiDesk,
  'gi/GiDungeonGate': GiDungeonGate,
  'gi/GiFamilyHouse': GiFamilyHouse,
  'gi/GiFairyWand': GiFairyWand,
  'gi/GiFloatingPlatforms': GiFloatingPlatforms,
  'gi/GiFloorHatch': GiFloorHatch,
  'gi/GiGate': GiGate,
  'gi/GiForest': GiForest,
  'gi/GiGearHammer': GiGearHammer,
  'gi/GiGlowingArtifact': GiGlowingArtifact,
  'gi/GiHarborDock': GiHarborDock,
  'gi/GiHidden': GiHidden,
  'gi/GiHutsVillage': GiHutsVillage,
  'gi/GiIsland': GiIsland,
  'gi/GiKitchenKnives': GiKitchenKnives,
  'gi/GiMedievalBarracks': GiMedievalBarracks,
  'gi/GiMedievalGate': GiMedievalGate,
  'gi/GiMineWagon': GiMineWagon,
  'gi/GiMaze': GiMaze,
  'gi/GiFruitTree': GiFruitTree,
  'gi/GiDjedPillar': GiDjedPillar,
  'gi/GiWaterfall': GiWaterfall,
  'gi/GiStonePath': GiStonePath,
  'gi/GiCampfire': GiCampfire,
  'gi/GiMountainCave': GiMountainCave,
  'gi/GiMountains': GiMountains,
  'gi/GiMountaintop': GiMountaintop,
  'gi/GiPuzzle': GiPuzzle,
  'gi/GiOpenGate': GiOpenGate,
  'gi/GiPokerHand': GiPokerHand,
  'gi/GiPrayer': GiPrayer,
  'gi/GiSailboat': GiSailboat,
  'gi/GiShadowGrasp': GiShadowGrasp,
  'gi/GiSpectre': GiSpectre,
  'gi/GiShop': GiShop,
  'gi/GiShower': GiShower,
  'gi/GiStable': GiStable,
  'gi/GiStalactites': GiStalactites,
  'gi/GiStoneTower': GiStoneTower,
  'gi/GiThroneKing': GiThroneKing,
  'gi/GiTripleGate': GiTripleGate,
  'gi/GiTwoShadows': GiTwoShadows,
  'gi/GiSwordsEmblem': GiSwordsEmblem,
  'gi/GiTempleDoor': GiTempleDoor,
  'gi/GiTempleGate': GiTempleGate,
  'gi/GiUndergroundCave': GiUndergroundCave,
  'gi/GiVillage': GiVillage,
  'gi/GiWaterFountain': GiWaterFountain,
  'gi/GiWaves': GiWaves,
  'gi/GiWhirlwind': GiWhirlwind,
  'gi/GiBlood': GiBlood,
  [LOCATION_ICON_PLACEHOLDER]: FaMapMarkerAlt,
}

export function resolveLocationIcon(icon?: string): LocationGlyph {
  return (icon ? LOCATION_ICONS[icon] : undefined) ?? LOCATION_ICONS[LOCATION_ICON_PLACEHOLDER]
}

/** Inline location glyph for tree rows and map pins. */
export function LocationIcon({ icon, className }: { icon?: string; className?: string }) {
  const Icon = resolveLocationIcon(icon)
  return <Icon className={cn('size-3.5 shrink-0', className)} aria-hidden />
}
