import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(import.meta.dirname, '..')
export const GENERATED_REFS_PATH = path.join(ROOT, 'src/data/generated/refs.ts')
const ENTITY_KINDS_PATH = path.join(ROOT, 'src/definitions/kind.ts')

const COLLECTIONS = [
  { kind: 'beast', plural: 'beasts', typeName: 'BeastKey' },
  { kind: 'event', plural: 'events', typeName: 'EventKey' },
  { kind: 'npc', plural: 'npcs', typeName: 'NpcKey' },
  { kind: 'pc', plural: 'pcs', typeName: 'PcKey' },
  { kind: 'location', plural: 'locations', typeName: 'LocationKey' },
  { kind: 'quest', plural: 'quests', typeName: 'QuestKey' },
  { kind: 'session', plural: 'sessions', typeName: 'SessionKey' },
  { kind: 'organization', plural: 'organizations', typeName: 'OrganizationKey' },
  { kind: 'item', plural: 'items', typeName: 'ItemKey' },
] as const

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/

export const REFERENCE_SOURCE_PATHS = [
  ENTITY_KINDS_PATH,
  ...COLLECTIONS.map(({ plural }) => path.join(ROOT, 'src/data', plural, '_index.ts')),
]

async function registryKeys(plural: string): Promise<string[]> {
  const registryPath = path.join(ROOT, 'src/data', plural, '_index.ts')
  const source = await readFile(registryPath, 'utf8')
  const match = /export default\s*\{(?<body>[\s\S]*?)\}/u.exec(source)

  if (!match?.groups?.body) {
    throw new Error(
      `Could not find the default registry object in ${path.relative(ROOT, registryPath)}`,
    )
  }

  const keys = match.groups.body
    .split(',')
    .map((entry) => entry.trim())
    .filter(Boolean)

  const invalidKey = keys.find((key) => !IDENTIFIER.test(key))
  if (invalidKey) {
    throw new Error(
      `Unsupported registry entry ${JSON.stringify(invalidKey)} in ${path.relative(ROOT, registryPath)}; use shorthand identifier entries`,
    )
  }

  if (new Set(keys).size !== keys.length) {
    throw new Error(`Duplicate registry entry in ${path.relative(ROOT, registryPath)}`)
  }

  return keys
}

async function assertAllEntityKindsAreConfigured(): Promise<void> {
  const source = await readFile(ENTITY_KINDS_PATH, 'utf8')
  const match = /export const ENTITY_KINDS\s*=\s*\[(?<body>[\s\S]*?)\]\s*as const/u.exec(source)

  if (!match?.groups?.body) {
    throw new Error(`Could not read ENTITY_KINDS from ${path.relative(ROOT, ENTITY_KINDS_PATH)}`)
  }

  const entityKinds = [...match.groups.body.matchAll(/['"](?<kind>[\w-]+)['"]/gu)].map(
    ({ groups }) => groups?.kind,
  )
  const configuredKinds = COLLECTIONS.map(({ kind }) => kind)

  if (
    entityKinds.length !== configuredKinds.length ||
    entityKinds.some(
      (kind) => !kind || !configuredKinds.includes(kind as (typeof configuredKinds)[number]),
    )
  ) {
    throw new Error(
      `Reference generator collections do not match ENTITY_KINDS. Expected: ${entityKinds.join(', ')}`,
    )
  }
}

async function generatedSource(): Promise<string> {
  await assertAllEntityKindsAreConfigured()

  const collections = await Promise.all(
    COLLECTIONS.map(async ({ kind, plural, typeName }) => ({
      kind,
      plural,
      typeName,
      keys: await registryKeys(plural),
    })),
  )

  const namespaces = collections
    .map(
      ({ kind, plural, keys }) =>
        `  ${plural}: {\n${keys.map((key) => `    ${key}: ref('${kind}', '${key}'),`).join('\n')}\n  },`,
    )
    .join('\n')

  const keyTypes = collections
    .map(({ plural, typeName }) => `export type ${typeName} = keyof typeof refs.${plural}`)
    .join('\n')

  return `// GENERATED FILE — DO NOT EDIT.
// Generated by \`bun run generate:refs\` from the entity registries in \`src/data/*/_index.ts\`.
// Regenerate after adding, removing, renaming, or re-keying any referenceable entity.

import type { EntityKind, EntityRef } from '#/definitions/kind.ts'

function ref(kind: EntityKind, key: string): EntityRef {
  return { ref: kind, key }
}

export const refs = {
${namespaces}
} as const

${keyTypes}
`
}

export async function generateRefs(options: { check?: boolean } = {}): Promise<boolean> {
  const expected = await generatedSource()
  const current = await readFile(GENERATED_REFS_PATH, 'utf8').catch(() => '')

  if (current === expected) return false

  if (options.check) {
    throw new Error(
      'Generated references are stale. Run `bun run generate:refs` and commit the result.',
    )
  }

  await mkdir(path.dirname(GENERATED_REFS_PATH), { recursive: true })
  await writeFile(GENERATED_REFS_PATH, expected)
  return true
}

const invokedPath = process.argv[1] ? path.resolve(process.argv[1]) : undefined
const isCli = invokedPath === fileURLToPath(import.meta.url)

if (isCli) {
  const checkOnly = process.argv.includes('--check')

  try {
    const changed = await generateRefs({ check: checkOnly })
    if (!checkOnly) {
      console.log(
        changed
          ? `Generated ${path.relative(ROOT, GENERATED_REFS_PATH)}`
          : `${path.relative(ROOT, GENERATED_REFS_PATH)} is already current`,
      )
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : error)
    process.exitCode = 1
  }
}
