import { createHash } from 'node:crypto'
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'

import pngToIco from 'png-to-ico'
import sharp, { type Metadata } from 'sharp'
/* oxlint-disable no-await-in-loop -- bounded sequential encoding keeps peak memory predictable */

import {
  APP_ICON_BACKGROUND,
  RESPONSIVE_IMAGE_ENCODING,
  RESPONSIVE_IMAGE_SOURCES,
  RESPONSIVE_IMAGE_WIDTHS,
} from './image-sources'

const ROOT = process.cwd()
const OUTPUT_DIRECTORY = join(ROOT, 'public/assets/generated-images')
const GENERATED_MODULE = join(ROOT, 'src/generated/responsive-images.ts')
const PIPELINE_VERSION = 'responsive-jpeg-v2|sharp@0.35.3|accurate-shrink'

type Candidate = {
  src: string
  width: number
  height: number
  bytes: number
}

type GeneratedImage = {
  width: number
  height: number
  quality: number
  progressive: true
  chromaSubsampling: '4:2:0'
  candidates: Candidate[]
}

function orientedDimensions(metadata: Metadata): { width: number; height: number } {
  if (!metadata.width || !metadata.height) throw new Error('Responsive image has no dimensions')
  return metadata.orientation && metadata.orientation >= 5
    ? { width: metadata.height, height: metadata.width }
    : { width: metadata.width, height: metadata.height }
}

function candidateWidths(sourceWidth: number): number[] {
  const maximumWidth = RESPONSIVE_IMAGE_WIDTHS.at(-1) ?? sourceWidth
  const cappedWidth = Math.min(sourceWidth, maximumWidth)
  return [...RESPONSIVE_IMAGE_WIDTHS.filter((width) => width < cappedWidth), cappedWidth].filter(
    (width, index, widths) => index === 0 || width !== widths[index - 1],
  )
}

async function generateContentImages(): Promise<Record<string, GeneratedImage>> {
  await rm(OUTPUT_DIRECTORY, { recursive: true, force: true })
  await mkdir(OUTPUT_DIRECTORY, { recursive: true })

  const generated: Record<string, GeneratedImage> = {}
  for (const source of RESPONSIVE_IMAGE_SOURCES) {
    const sourceBytes = await readFile(join(ROOT, source.repositoryPath))
    const dimensions = orientedDimensions(await sharp(sourceBytes).metadata())
    const digest = createHash('sha256')
      .update(sourceBytes)
      .update(PIPELINE_VERSION)
      .update(JSON.stringify(RESPONSIVE_IMAGE_ENCODING))
      .digest('hex')
      .slice(0, 16)
    const candidates: Candidate[] = []

    for (const width of candidateWidths(dimensions.width)) {
      const output = await sharp(sourceBytes)
        .rotate()
        // JPEG shrink-on-load can round a dimension before the final resize.
        .resize({ width, withoutEnlargement: true, fastShrinkOnLoad: false })
        .flatten({ background: APP_ICON_BACKGROUND })
        .jpeg({
          quality: RESPONSIVE_IMAGE_ENCODING.quality,
          progressive: RESPONSIVE_IMAGE_ENCODING.progressive,
          chromaSubsampling: RESPONSIVE_IMAGE_ENCODING.chromaSubsampling,
        })
        .toBuffer({ resolveWithObject: true })
      const fileName = `${source.id}.${digest}.w${output.info.width}.jpg`
      await writeFile(join(OUTPUT_DIRECTORY, fileName), output.data)
      candidates.push({
        src: `/assets/generated-images/${fileName}`,
        width: output.info.width,
        height: output.info.height,
        bytes: output.data.byteLength,
      })
    }

    generated[source.logicalSource] = {
      ...dimensions,
      ...RESPONSIVE_IMAGE_ENCODING,
      candidates,
    }
  }
  return generated
}

async function generateOpaqueAppIcons(): Promise<void> {
  const source = await readFile(join(ROOT, 'assets/images/app/logo512.png'))
  const logo192 = await sharp(source)
    .resize(192, 192)
    .flatten({ background: APP_ICON_BACKGROUND })
    .png({ compressionLevel: 9 })
    .toBuffer()
  const logo512 = await sharp(source)
    .resize(512, 512)
    .flatten({ background: APP_ICON_BACKGROUND })
    .png({ compressionLevel: 9 })
    .toBuffer()
  const faviconPng = await sharp(source)
    .resize(256, 256)
    .flatten({ background: APP_ICON_BACKGROUND })
    .png({ compressionLevel: 9 })
    .toBuffer()

  await Promise.all([
    writeFile(join(ROOT, 'public/logo192.png'), logo192),
    writeFile(join(ROOT, 'public/logo512.png'), logo512),
    writeFile(join(ROOT, 'public/favicon.ico'), await pngToIco(faviconPng)),
  ])
}

async function generate(): Promise<void> {
  const startedAt = performance.now()
  const generated = await generateContentImages()
  await generateOpaqueAppIcons()
  await mkdir(dirname(GENERATED_MODULE), { recursive: true })
  await writeFile(
    GENERATED_MODULE,
    `// Generated by scripts/generate-responsive-images.ts. Do not edit.\nexport const GENERATED_RESPONSIVE_IMAGES = ${JSON.stringify(generated, null, 2)} as const\n`,
  )

  const outputFiles = await readdir(OUTPUT_DIRECTORY)
  const sourceBytes = (
    await Promise.all(
      RESPONSIVE_IMAGE_SOURCES.map(
        async ({ repositoryPath }) => (await readFile(join(ROOT, repositoryPath))).byteLength,
      ),
    )
  ).reduce((sum, bytes) => sum + bytes, 0)
  const smallestCandidateBytes = Object.values(generated).reduce(
    (sum, image) => sum + (image.candidates[0]?.bytes ?? 0),
    0,
  )
  console.log(
    `Generated ${outputFiles.length} progressive JPEGs for ${RESPONSIVE_IMAGE_SOURCES.length} sources in ${Math.round(performance.now() - startedAt)} ms (${sourceBytes} source bytes; ${smallestCandidateBytes} bytes across smallest candidates)`,
  )
}

await generate()
