/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as QuestsIndexRouteImport } from './routes/quests/index'
import { Route as PcsIndexRouteImport } from './routes/pcs/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as NpcsIndexRouteImport } from './routes/npcs/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as BeastsIndexRouteImport } from './routes/beasts/index'
import { Route as LocationsMapRouteImport } from './routes/locations/map'
import { Route as LocationsListRouteImport } from './routes/locations/list'
import { Route as SessionsDetailSlugRouteImport } from './routes/sessions/detail.$slug'
import { Route as QuestsDetailSlugRouteImport } from './routes/quests/detail.$slug'
import { Route as PcsDetailSlugRouteImport } from './routes/pcs/detail.$slug'
import { Route as OrganizationsDetailSlugRouteImport } from './routes/organizations/detail.$slug'
import { Route as NpcsDetailSlugRouteImport } from './routes/npcs/detail.$slug'
import { Route as LocationsDetailSlugRouteImport } from './routes/locations/detail.$slug'
import { Route as EventsDetailSlugRouteImport } from './routes/events/detail.$slug'
import { Route as BeastsDetailSlugRouteImport } from './routes/beasts/detail.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsIndexRoute = QuestsIndexRouteImport.update({
  id: '/quests/',
  path: '/quests/',
  getParentRoute: () => rootRouteImport,
} as any)
const PcsIndexRoute = PcsIndexRouteImport.update({
  id: '/pcs/',
  path: '/pcs/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const NpcsIndexRoute = NpcsIndexRouteImport.update({
  id: '/npcs/',
  path: '/npcs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeastsIndexRoute = BeastsIndexRouteImport.update({
  id: '/beasts/',
  path: '/beasts/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsMapRoute = LocationsMapRouteImport.update({
  id: '/locations/map',
  path: '/locations/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsListRoute = LocationsListRouteImport.update({
  id: '/locations/list',
  path: '/locations/list',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsDetailSlugRoute = SessionsDetailSlugRouteImport.update({
  id: '/sessions/detail/$slug',
  path: '/sessions/detail/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsDetailSlugRoute = QuestsDetailSlugRouteImport.update({
  id: '/quests/detail/$slug',
  path: '/quests/detail/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PcsDetailSlugRoute = PcsDetailSlugRouteImport.update({
  id: '/pcs/detail/$slug',
  path: '/pcs/detail/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsDetailSlugRoute = OrganizationsDetailSlugRouteImport.update({
  id: '/organizations/detail/$slug',
  path: '/organizations/detail/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NpcsDetailSlugRoute = NpcsDetailSlugRouteImport.update({
  id: '/npcs/detail/$slug',
  path: '/npcs/detail/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsDetailSlugRoute = LocationsDetailSlugRouteImport.update({
  id: '/locations/detail/$slug',
  path: '/locations/detail/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsDetailSlugRoute = EventsDetailSlugRouteImport.update({
  id: '/events/detail/$slug',
  path: '/events/detail/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BeastsDetailSlugRoute = BeastsDetailSlugRouteImport.update({
  id: '/beasts/detail/$slug',
  path: '/beasts/detail/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/locations/list': typeof LocationsListRoute
  '/locations/map': typeof LocationsMapRoute
  '/beasts/': typeof BeastsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/npcs/': typeof NpcsIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/pcs/': typeof PcsIndexRoute
  '/quests/': typeof QuestsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/beasts/detail/$slug': typeof BeastsDetailSlugRoute
  '/events/detail/$slug': typeof EventsDetailSlugRoute
  '/locations/detail/$slug': typeof LocationsDetailSlugRoute
  '/npcs/detail/$slug': typeof NpcsDetailSlugRoute
  '/organizations/detail/$slug': typeof OrganizationsDetailSlugRoute
  '/pcs/detail/$slug': typeof PcsDetailSlugRoute
  '/quests/detail/$slug': typeof QuestsDetailSlugRoute
  '/sessions/detail/$slug': typeof SessionsDetailSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/locations/list': typeof LocationsListRoute
  '/locations/map': typeof LocationsMapRoute
  '/beasts': typeof BeastsIndexRoute
  '/events': typeof EventsIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/npcs': typeof NpcsIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/pcs': typeof PcsIndexRoute
  '/quests': typeof QuestsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/beasts/detail/$slug': typeof BeastsDetailSlugRoute
  '/events/detail/$slug': typeof EventsDetailSlugRoute
  '/locations/detail/$slug': typeof LocationsDetailSlugRoute
  '/npcs/detail/$slug': typeof NpcsDetailSlugRoute
  '/organizations/detail/$slug': typeof OrganizationsDetailSlugRoute
  '/pcs/detail/$slug': typeof PcsDetailSlugRoute
  '/quests/detail/$slug': typeof QuestsDetailSlugRoute
  '/sessions/detail/$slug': typeof SessionsDetailSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/locations/list': typeof LocationsListRoute
  '/locations/map': typeof LocationsMapRoute
  '/beasts/': typeof BeastsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/npcs/': typeof NpcsIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/pcs/': typeof PcsIndexRoute
  '/quests/': typeof QuestsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/beasts/detail/$slug': typeof BeastsDetailSlugRoute
  '/events/detail/$slug': typeof EventsDetailSlugRoute
  '/locations/detail/$slug': typeof LocationsDetailSlugRoute
  '/npcs/detail/$slug': typeof NpcsDetailSlugRoute
  '/organizations/detail/$slug': typeof OrganizationsDetailSlugRoute
  '/pcs/detail/$slug': typeof PcsDetailSlugRoute
  '/quests/detail/$slug': typeof QuestsDetailSlugRoute
  '/sessions/detail/$slug': typeof SessionsDetailSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/locations/list'
    | '/locations/map'
    | '/beasts/'
    | '/events/'
    | '/locations/'
    | '/npcs/'
    | '/organizations/'
    | '/pcs/'
    | '/quests/'
    | '/sessions/'
    | '/beasts/detail/$slug'
    | '/events/detail/$slug'
    | '/locations/detail/$slug'
    | '/npcs/detail/$slug'
    | '/organizations/detail/$slug'
    | '/pcs/detail/$slug'
    | '/quests/detail/$slug'
    | '/sessions/detail/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/locations/list'
    | '/locations/map'
    | '/beasts'
    | '/events'
    | '/locations'
    | '/npcs'
    | '/organizations'
    | '/pcs'
    | '/quests'
    | '/sessions'
    | '/beasts/detail/$slug'
    | '/events/detail/$slug'
    | '/locations/detail/$slug'
    | '/npcs/detail/$slug'
    | '/organizations/detail/$slug'
    | '/pcs/detail/$slug'
    | '/quests/detail/$slug'
    | '/sessions/detail/$slug'
  id:
    | '__root__'
    | '/'
    | '/locations/list'
    | '/locations/map'
    | '/beasts/'
    | '/events/'
    | '/locations/'
    | '/npcs/'
    | '/organizations/'
    | '/pcs/'
    | '/quests/'
    | '/sessions/'
    | '/beasts/detail/$slug'
    | '/events/detail/$slug'
    | '/locations/detail/$slug'
    | '/npcs/detail/$slug'
    | '/organizations/detail/$slug'
    | '/pcs/detail/$slug'
    | '/quests/detail/$slug'
    | '/sessions/detail/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocationsListRoute: typeof LocationsListRoute
  LocationsMapRoute: typeof LocationsMapRoute
  BeastsIndexRoute: typeof BeastsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  NpcsIndexRoute: typeof NpcsIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  PcsIndexRoute: typeof PcsIndexRoute
  QuestsIndexRoute: typeof QuestsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  BeastsDetailSlugRoute: typeof BeastsDetailSlugRoute
  EventsDetailSlugRoute: typeof EventsDetailSlugRoute
  LocationsDetailSlugRoute: typeof LocationsDetailSlugRoute
  NpcsDetailSlugRoute: typeof NpcsDetailSlugRoute
  OrganizationsDetailSlugRoute: typeof OrganizationsDetailSlugRoute
  PcsDetailSlugRoute: typeof PcsDetailSlugRoute
  QuestsDetailSlugRoute: typeof QuestsDetailSlugRoute
  SessionsDetailSlugRoute: typeof SessionsDetailSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/': {
      id: '/quests/'
      path: '/quests'
      fullPath: '/quests/'
      preLoaderRoute: typeof QuestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pcs/': {
      id: '/pcs/'
      path: '/pcs'
      fullPath: '/pcs/'
      preLoaderRoute: typeof PcsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npcs/': {
      id: '/npcs/'
      path: '/npcs'
      fullPath: '/npcs/'
      preLoaderRoute: typeof NpcsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beasts/': {
      id: '/beasts/'
      path: '/beasts'
      fullPath: '/beasts/'
      preLoaderRoute: typeof BeastsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/map': {
      id: '/locations/map'
      path: '/locations/map'
      fullPath: '/locations/map'
      preLoaderRoute: typeof LocationsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/list': {
      id: '/locations/list'
      path: '/locations/list'
      fullPath: '/locations/list'
      preLoaderRoute: typeof LocationsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/detail/$slug': {
      id: '/sessions/detail/$slug'
      path: '/sessions/detail/$slug'
      fullPath: '/sessions/detail/$slug'
      preLoaderRoute: typeof SessionsDetailSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/detail/$slug': {
      id: '/quests/detail/$slug'
      path: '/quests/detail/$slug'
      fullPath: '/quests/detail/$slug'
      preLoaderRoute: typeof QuestsDetailSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pcs/detail/$slug': {
      id: '/pcs/detail/$slug'
      path: '/pcs/detail/$slug'
      fullPath: '/pcs/detail/$slug'
      preLoaderRoute: typeof PcsDetailSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/detail/$slug': {
      id: '/organizations/detail/$slug'
      path: '/organizations/detail/$slug'
      fullPath: '/organizations/detail/$slug'
      preLoaderRoute: typeof OrganizationsDetailSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npcs/detail/$slug': {
      id: '/npcs/detail/$slug'
      path: '/npcs/detail/$slug'
      fullPath: '/npcs/detail/$slug'
      preLoaderRoute: typeof NpcsDetailSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/detail/$slug': {
      id: '/locations/detail/$slug'
      path: '/locations/detail/$slug'
      fullPath: '/locations/detail/$slug'
      preLoaderRoute: typeof LocationsDetailSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/detail/$slug': {
      id: '/events/detail/$slug'
      path: '/events/detail/$slug'
      fullPath: '/events/detail/$slug'
      preLoaderRoute: typeof EventsDetailSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beasts/detail/$slug': {
      id: '/beasts/detail/$slug'
      path: '/beasts/detail/$slug'
      fullPath: '/beasts/detail/$slug'
      preLoaderRoute: typeof BeastsDetailSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocationsListRoute: LocationsListRoute,
  LocationsMapRoute: LocationsMapRoute,
  BeastsIndexRoute: BeastsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  NpcsIndexRoute: NpcsIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  PcsIndexRoute: PcsIndexRoute,
  QuestsIndexRoute: QuestsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  BeastsDetailSlugRoute: BeastsDetailSlugRoute,
  EventsDetailSlugRoute: EventsDetailSlugRoute,
  LocationsDetailSlugRoute: LocationsDetailSlugRoute,
  NpcsDetailSlugRoute: NpcsDetailSlugRoute,
  OrganizationsDetailSlugRoute: OrganizationsDetailSlugRoute,
  PcsDetailSlugRoute: PcsDetailSlugRoute,
  QuestsDetailSlugRoute: QuestsDetailSlugRoute,
  SessionsDetailSlugRoute: SessionsDetailSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
