/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as QuestsIndexRouteImport } from './routes/quests/index'
import { Route as PcsIndexRouteImport } from './routes/pcs/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as NpcsIndexRouteImport } from './routes/npcs/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as SessionsSlugRouteImport } from './routes/sessions/$slug'
import { Route as QuestsSlugRouteImport } from './routes/quests/$slug'
import { Route as PcsSlugRouteImport } from './routes/pcs/$slug'
import { Route as OrganizationsSlugRouteImport } from './routes/organizations/$slug'
import { Route as NpcsSlugRouteImport } from './routes/npcs/$slug'
import { Route as LocationsMapRouteImport } from './routes/locations/map'
import { Route as LocationsListRouteImport } from './routes/locations/list'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'
import { Route as LocationsDetailSlugRouteImport } from './routes/locations/detail.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsIndexRoute = QuestsIndexRouteImport.update({
  id: '/quests/',
  path: '/quests/',
  getParentRoute: () => rootRouteImport,
} as any)
const PcsIndexRoute = PcsIndexRouteImport.update({
  id: '/pcs/',
  path: '/pcs/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const NpcsIndexRoute = NpcsIndexRouteImport.update({
  id: '/npcs/',
  path: '/npcs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSlugRoute = SessionsSlugRouteImport.update({
  id: '/sessions/$slug',
  path: '/sessions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsSlugRoute = QuestsSlugRouteImport.update({
  id: '/quests/$slug',
  path: '/quests/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PcsSlugRoute = PcsSlugRouteImport.update({
  id: '/pcs/$slug',
  path: '/pcs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsSlugRoute = OrganizationsSlugRouteImport.update({
  id: '/organizations/$slug',
  path: '/organizations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NpcsSlugRoute = NpcsSlugRouteImport.update({
  id: '/npcs/$slug',
  path: '/npcs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsMapRoute = LocationsMapRouteImport.update({
  id: '/locations/map',
  path: '/locations/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsListRoute = LocationsListRouteImport.update({
  id: '/locations/list',
  path: '/locations/list',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsDetailSlugRoute = LocationsDetailSlugRouteImport.update({
  id: '/locations/detail/$slug',
  path: '/locations/detail/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$slug': typeof EventsSlugRoute
  '/locations/list': typeof LocationsListRoute
  '/locations/map': typeof LocationsMapRoute
  '/npcs/$slug': typeof NpcsSlugRoute
  '/organizations/$slug': typeof OrganizationsSlugRoute
  '/pcs/$slug': typeof PcsSlugRoute
  '/quests/$slug': typeof QuestsSlugRoute
  '/sessions/$slug': typeof SessionsSlugRoute
  '/events/': typeof EventsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/npcs/': typeof NpcsIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/pcs/': typeof PcsIndexRoute
  '/quests/': typeof QuestsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/locations/detail/$slug': typeof LocationsDetailSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$slug': typeof EventsSlugRoute
  '/locations/list': typeof LocationsListRoute
  '/locations/map': typeof LocationsMapRoute
  '/npcs/$slug': typeof NpcsSlugRoute
  '/organizations/$slug': typeof OrganizationsSlugRoute
  '/pcs/$slug': typeof PcsSlugRoute
  '/quests/$slug': typeof QuestsSlugRoute
  '/sessions/$slug': typeof SessionsSlugRoute
  '/events': typeof EventsIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/npcs': typeof NpcsIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/pcs': typeof PcsIndexRoute
  '/quests': typeof QuestsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/locations/detail/$slug': typeof LocationsDetailSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/$slug': typeof EventsSlugRoute
  '/locations/list': typeof LocationsListRoute
  '/locations/map': typeof LocationsMapRoute
  '/npcs/$slug': typeof NpcsSlugRoute
  '/organizations/$slug': typeof OrganizationsSlugRoute
  '/pcs/$slug': typeof PcsSlugRoute
  '/quests/$slug': typeof QuestsSlugRoute
  '/sessions/$slug': typeof SessionsSlugRoute
  '/events/': typeof EventsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/npcs/': typeof NpcsIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/pcs/': typeof PcsIndexRoute
  '/quests/': typeof QuestsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/locations/detail/$slug': typeof LocationsDetailSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/$slug'
    | '/locations/list'
    | '/locations/map'
    | '/npcs/$slug'
    | '/organizations/$slug'
    | '/pcs/$slug'
    | '/quests/$slug'
    | '/sessions/$slug'
    | '/events/'
    | '/locations/'
    | '/npcs/'
    | '/organizations/'
    | '/pcs/'
    | '/quests/'
    | '/sessions/'
    | '/locations/detail/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events/$slug'
    | '/locations/list'
    | '/locations/map'
    | '/npcs/$slug'
    | '/organizations/$slug'
    | '/pcs/$slug'
    | '/quests/$slug'
    | '/sessions/$slug'
    | '/events'
    | '/locations'
    | '/npcs'
    | '/organizations'
    | '/pcs'
    | '/quests'
    | '/sessions'
    | '/locations/detail/$slug'
  id:
    | '__root__'
    | '/'
    | '/events/$slug'
    | '/locations/list'
    | '/locations/map'
    | '/npcs/$slug'
    | '/organizations/$slug'
    | '/pcs/$slug'
    | '/quests/$slug'
    | '/sessions/$slug'
    | '/events/'
    | '/locations/'
    | '/npcs/'
    | '/organizations/'
    | '/pcs/'
    | '/quests/'
    | '/sessions/'
    | '/locations/detail/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsSlugRoute: typeof EventsSlugRoute
  LocationsListRoute: typeof LocationsListRoute
  LocationsMapRoute: typeof LocationsMapRoute
  NpcsSlugRoute: typeof NpcsSlugRoute
  OrganizationsSlugRoute: typeof OrganizationsSlugRoute
  PcsSlugRoute: typeof PcsSlugRoute
  QuestsSlugRoute: typeof QuestsSlugRoute
  SessionsSlugRoute: typeof SessionsSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  NpcsIndexRoute: typeof NpcsIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  PcsIndexRoute: typeof PcsIndexRoute
  QuestsIndexRoute: typeof QuestsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  LocationsDetailSlugRoute: typeof LocationsDetailSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/': {
      id: '/quests/'
      path: '/quests'
      fullPath: '/quests/'
      preLoaderRoute: typeof QuestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pcs/': {
      id: '/pcs/'
      path: '/pcs'
      fullPath: '/pcs/'
      preLoaderRoute: typeof PcsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npcs/': {
      id: '/npcs/'
      path: '/npcs'
      fullPath: '/npcs/'
      preLoaderRoute: typeof NpcsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$slug': {
      id: '/sessions/$slug'
      path: '/sessions/$slug'
      fullPath: '/sessions/$slug'
      preLoaderRoute: typeof SessionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/$slug': {
      id: '/quests/$slug'
      path: '/quests/$slug'
      fullPath: '/quests/$slug'
      preLoaderRoute: typeof QuestsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pcs/$slug': {
      id: '/pcs/$slug'
      path: '/pcs/$slug'
      fullPath: '/pcs/$slug'
      preLoaderRoute: typeof PcsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$slug': {
      id: '/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof OrganizationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npcs/$slug': {
      id: '/npcs/$slug'
      path: '/npcs/$slug'
      fullPath: '/npcs/$slug'
      preLoaderRoute: typeof NpcsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/map': {
      id: '/locations/map'
      path: '/locations/map'
      fullPath: '/locations/map'
      preLoaderRoute: typeof LocationsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/list': {
      id: '/locations/list'
      path: '/locations/list'
      fullPath: '/locations/list'
      preLoaderRoute: typeof LocationsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/detail/$slug': {
      id: '/locations/detail/$slug'
      path: '/locations/detail/$slug'
      fullPath: '/locations/detail/$slug'
      preLoaderRoute: typeof LocationsDetailSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsSlugRoute: EventsSlugRoute,
  LocationsListRoute: LocationsListRoute,
  LocationsMapRoute: LocationsMapRoute,
  NpcsSlugRoute: NpcsSlugRoute,
  OrganizationsSlugRoute: OrganizationsSlugRoute,
  PcsSlugRoute: PcsSlugRoute,
  QuestsSlugRoute: QuestsSlugRoute,
  SessionsSlugRoute: SessionsSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  NpcsIndexRoute: NpcsIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  PcsIndexRoute: PcsIndexRoute,
  QuestsIndexRoute: QuestsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  LocationsDetailSlugRoute: LocationsDetailSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
